# Generated by Django 6.0.3 on 2026-03-09 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Dermatologista', 'Dermatologista'), ('Endocrinologista', 'Endocrinologista'), ('Ginecologista', 'Ginecologista'), ('Mastologista', 'Mastologista'), ('Neurologista', 'Neurologista'), ('Ortopedista', 'Ortopedista'), ('Urologista', 'Urologista'), ('Cir. Vascular', 'Cir. Vascular'), ('Gastroenterologista', 'Gastroenterologista'), ('Reumatologista', 'Reumatologista'), ('Oftalmologista', 'Oftalmologista'), ('Otorrinolaringologista', 'Otorrinolaringologista')], max_length=50)),
                ('data', models.DateField()),
                ('total_vagas', models.IntegerField()),
                ('vagas_por_ubs', models.IntegerField()),
                ('vagas_regulacao', models.IntegerField()),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='andamento', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubs', models.CharField(choices=[('Centro 1', 'Centro 1'), ('Centro 2', 'Centro 2'), ('Sertãozinho 1', 'Sertãozinho 1'), ('Sertãozinho 2', 'Sertãozinho 2'), ('Jiqui 1', 'Jiqui 1'), ('Jiqui 2', 'Jiqui 2'), ('Areia Branca 1', 'Areia Branca 1'), ('Areia Branca 2', 'Areia Branca 2'), ('Areia Branca 3', 'Areia Branca 3'), ('Lagoa de São João', 'Lagoa de São João'), ('Barra do Cunhaú', 'Barra do Cunhaú'), ('Outeiro', 'Outeiro'), ('Piquiri 1', 'Piquiri 1'), ('Piquiri 2', 'Piquiri 2'), ('Piquiri 3', 'Piquiri 3'), ('Meira Lima 1', 'Meira Lima 1'), ('Meira Lima 2', 'Meira Lima 2'), ('Regulação', 'Regulação')], max_length=50)),
                ('nome', models.CharField(max_length=200)),
                ('sus', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('agente', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agenda')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaUBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubs', models.CharField(choices=[('Centro 1', 'Centro 1'), ('Centro 2', 'Centro 2'), ('Sertãozinho 1', 'Sertãozinho 1'), ('Sertãozinho 2', 'Sertãozinho 2'), ('Jiqui 1', 'Jiqui 1'), ('Jiqui 2', 'Jiqui 2'), ('Areia Branca 1', 'Areia Branca 1'), ('Areia Branca 2', 'Areia Branca 2'), ('Areia Branca 3', 'Areia Branca 3'), ('Lagoa de São João', 'Lagoa de São João'), ('Barra do Cunhaú', 'Barra do Cunhaú'), ('Outeiro', 'Outeiro'), ('Piquiri 1', 'Piquiri 1'), ('Piquiri 2', 'Piquiri 2'), ('Piquiri 3', 'Piquiri 3'), ('Meira Lima 1', 'Meira Lima 1'), ('Meira Lima 2', 'Meira Lima 2'), ('Regulação', 'Regulação')], max_length=50)),
                ('vagas', models.IntegerField()),
                ('vagas_usadas', models.IntegerField(default=0)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agenda')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteCirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=200)),
                ('sus', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=20)),
                ('ubs', models.CharField(choices=[('Centro 1', 'Centro 1'), ('Centro 2', 'Centro 2'), ('Sertãozinho 1', 'Sertãozinho 1'), ('Sertãozinho 2', 'Sertãozinho 2'), ('Jiqui 1', 'Jiqui 1'), ('Jiqui 2', 'Jiqui 2'), ('Areia Branca 1', 'Areia Branca 1'), ('Areia Branca 2', 'Areia Branca 2'), ('Areia Branca 3', 'Areia Branca 3'), ('Lagoa de São João', 'Lagoa de São João'), ('Barra do Cunhaú', 'Barra do Cunhaú'), ('Outeiro', 'Outeiro'), ('Piquiri 1', 'Piquiri 1'), ('Piquiri 2', 'Piquiri 2'), ('Piquiri 3', 'Piquiri 3'), ('Meira Lima 1', 'Meira Lima 1'), ('Meira Lima 2', 'Meira Lima 2'), ('Regulação', 'Regulação')], max_length=50)),
                ('agente_saude', models.CharField(blank=True, max_length=100)),
                ('cirurgia', models.CharField(choices=[('Cabeça e Pescoço', 'Cabeça e Pescoço'), ('Ginecologia', 'Ginecologia'), ('Hérnia', 'Hérnia'), ('Vesícula', 'Vesícula'), ('Ortopédica', 'Ortopédica'), ('Urológica', 'Urológica'), ('Pediátrica', 'Pediátrica'), ('Neurológica', 'Neurológica'), ('Pequena Cirurgia', 'Pequena Cirurgia'), ('Cardíaca', 'Cardíaca'), ('Plástica', 'Plástica')], max_length=50)),
                ('protocolo', models.CharField(blank=True, max_length=50, unique=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=200)),
                ('sus', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=20)),
                ('ubs', models.CharField(choices=[('Centro 1', 'Centro 1'), ('Centro 2', 'Centro 2'), ('Sertãozinho 1', 'Sertãozinho 1'), ('Sertãozinho 2', 'Sertãozinho 2'), ('Jiqui 1', 'Jiqui 1'), ('Jiqui 2', 'Jiqui 2'), ('Areia Branca 1', 'Areia Branca 1'), ('Areia Branca 2', 'Areia Branca 2'), ('Areia Branca 3', 'Areia Branca 3'), ('Lagoa de São João', 'Lagoa de São João'), ('Barra do Cunhaú', 'Barra do Cunhaú'), ('Outeiro', 'Outeiro'), ('Piquiri 1', 'Piquiri 1'), ('Piquiri 2', 'Piquiri 2'), ('Piquiri 3', 'Piquiri 3'), ('Meira Lima 1', 'Meira Lima 1'), ('Meira Lima 2', 'Meira Lima 2'), ('Regulação', 'Regulação')], max_length=50)),
                ('agente_saude', models.CharField(blank=True, max_length=100)),
                ('especialidade', models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Dermatologista', 'Dermatologista'), ('Endocrinologista', 'Endocrinologista'), ('Ginecologista', 'Ginecologista'), ('Mastologista', 'Mastologista'), ('Neurologista', 'Neurologista'), ('Ortopedista', 'Ortopedista'), ('Urologista', 'Urologista'), ('Cir. Vascular', 'Cir. Vascular'), ('Gastroenterologista', 'Gastroenterologista'), ('Reumatologista', 'Reumatologista'), ('Oftalmologista', 'Oftalmologista'), ('Otorrinolaringologista', 'Otorrinolaringologista')], max_length=50)),
                ('protocolo', models.CharField(blank=True, max_length=50, unique=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=200)),
                ('sus', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=20)),
                ('ubs', models.CharField(choices=[('Centro 1', 'Centro 1'), ('Centro 2', 'Centro 2'), ('Sertãozinho 1', 'Sertãozinho 1'), ('Sertãozinho 2', 'Sertãozinho 2'), ('Jiqui 1', 'Jiqui 1'), ('Jiqui 2', 'Jiqui 2'), ('Areia Branca 1', 'Areia Branca 1'), ('Areia Branca 2', 'Areia Branca 2'), ('Areia Branca 3', 'Areia Branca 3'), ('Lagoa de São João', 'Lagoa de São João'), ('Barra do Cunhaú', 'Barra do Cunhaú'), ('Outeiro', 'Outeiro'), ('Piquiri 1', 'Piquiri 1'), ('Piquiri 2', 'Piquiri 2'), ('Piquiri 3', 'Piquiri 3'), ('Meira Lima 1', 'Meira Lima 1'), ('Meira Lima 2', 'Meira Lima 2'), ('Regulação', 'Regulação')], max_length=50)),
                ('agente_saude', models.CharField(blank=True, max_length=100)),
                ('exame', models.CharField(choices=[('Ultrassonografia', 'Ultrassonografia'), ('Endoscopia', 'Endoscopia'), ('Ecocardiograma', 'Ecocardiograma'), ('Tomografia', 'Tomografia'), ('Ressonância', 'Ressonância')], max_length=50)),
                ('protocolo', models.CharField(blank=True, max_length=50, unique=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
